from MyQR import myqr as mq
mq.run(words = 'http://127.0.0.1:5000/',
  version = 6,
  picture = 'C:/Users/91999/OneDrive/Desktop/THE ULTIMATE TRACKER/static/logo1.png',
  colorized = True,
  save_name = 'trackercode.png')
mq.run(words = 'http://127.0.0.1:5000/list/',
  version = 6,
  picture = 'C:/Users/91999/OneDrive/Desktop/THE ULTIMATE TRACKER/static/logo2.png',
  colorized = True,
  save_name = 'listcode.png')
mq.run(words = 'http://127.0.0.1:5000/wild-fire/',
  version = 6,
  colorized = True,
  save_name = 'wildfirecode.png')
mq.run(words = 'http://127.0.0.1:5000/volcanoes/',
  version = 6,
  colorized = True,
  save_name = 'volcanoescode.png')
mq.run(words = 'http://127.0.0.1:5000/severe-storms/',
  version = 6,
  colorized = True,
  save_name = 'stormscode.png')
mq.run(words = 'http://127.0.0.1:5000/icebergs/',
  version = 6,
  colorized = True,
  save_name = 'icebergcode.png')
